export const USER_POST_FETCH_REQUESTED = 'USER_POST_FETCH_REQUESTED'
export const USER_POST_FETCH_SUCCEEDED = 'USER_POST_FETCH_SUCCEEDED'
export const USER_POST_FETCH_FAILED = 'USER_POST_FETCH_FAILED'